name: sandwich_shop
description: "A Flutter project for a sandwich shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  sqflite: ^2.2.8
  path: ^1.8.4
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sandwiches.json